version: '3.4'

services:
  db:
    build:
      context: ${PWD}
      dockerfile: docker/db.Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
      APPLICATION_DB: ${APPLICATION_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} --host=${POSTGRES_HOSTNAME} --port=5432 || exit 1"
      interval: "2s"
      timeout: 10s
      start_period: "5s"
      retries: 5
  web:
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile.production
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_CONFIG: ${FLASK_CONFIG}
      FLASK_APP: ${FLASK_APP}
      APPLICATION_DB: ${APPLICATION_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOSTNAME: "db"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
    command: python manage.py run-server
    volumes:
      - ${PWD}:/opt/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - web
      
volumes:
  pgdata: