"""empty message

Revision ID: ad0a28fb4b68
Revises: 48f33ce32eb3
Create Date: 2021-09-13 23:05:13.954086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0a28fb4b68'
down_revision = '48f33ce32eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('expire', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'expire')
    # ### end Alembic commands ###
